version: '3'

services:
   jenkins:
     build:
      context: .
     ports:
       - "50000:50000"
       - "8080:8080"
     restart: always
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - ./data/jenkins:/var/jenkins_home

